  const wmc = "https://upload.wikimedia.org/wikipedia/commons";
  const o365 = "https://raw.githubusercontent.com/sempostma/office365-icons/refs/heads/master/svg";
  const data = { 
  "diasgc": [
    { "url": "https://diasgc.github.io/arec-z/", "icon": "../arec-z/icon.svg", "name": "AudioRec"},
    { "url": "https://diasgc.github.io/tl2/", "icon": "../tl2/icon.svg", "name": "TimeLapse"},
    { "url": "https://diasgc.github.io/zc/tnk", "icon": "../zc/tnk/icon.svg", "name": "TN'K", "user": "1"},
    { "url": "https://diasgc.github.io/wwp/", "icon": "../wwp/icon.svg", "name": "Weather"},
    { "url": "https://diasgc.github.io/hexv/", "icon": "../hexv/icon.svg", "name": "HexView"},
    { "url": "https://diasgc.github.io/compass/", "icon": "../compass/icon.svg", "name": "Compass"},
    { "url": "https://diasgc.github.io/level/", "icon": "../level/icon.svg", "name": "Level"},
    { "url": "https://diasgc.github.io/glsl/", "icon": "../glsl/glsl.svg", "name": "GLSL"},
    { "url": "https://diasgc.github.io/glsl/editor.html", "icon": "../glsl/editor.svg", "name": "WebGl"},
    { "url": "https://diasgc.github.io/sensor/", "icon": "../sensor/icon.svg", "name": "Sensors"},
    { "url": "https://diasgc.github.io/ubuntu-setup/res/", "icon": "../ubuntu-setup/res/icon.svg", "name": "UbuntuWp"},
    { "url": "https://diasgc.github.io/ubuntu-setup/sw/", "icon": "../ubuntu-setup/sw/icon.svg", "name": "UbuntuSetup"},
    { "url": "https://diasgc.github.io/color/", "icon": "../color/icon.svg", "name": "Color"},
  ],
  "AI": [
    { "name": "Gemini", "url": "https://gemini.google.com"},
    { "name": "Copilot", "url": "https://copilot.microsoft.com"},
    { "name": "Deepseek", "url": "https://chat.deepseek.com"},
    { "name": "ChatGPT", "url": "https://chatgpt.com"},
    { "name": "Perplexity", "url": "https://www.perplexity.ai", "background": "#111"},
    { "name": "Claude", "url": "https://claude.ai"},
    { "name": "Grok", "url": "https://grok.com"},
  ],
  "Browse" : [
    { "name": "Google", "url": "https://www.google.pt", "icon": "https://www.google.pt/images/branding/googleg/1x/googleg_standard_color_128dp.png"},
    { "name": "DuckDuckGo ", "url": "https://duckduckgo.com/", "icon": "https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/duckduckgo-icon.svg" },
    { "name": "Bing", "url": "https://www.bing.com/", "icon": `${wmc}/f/f3/Bing_Logo.svg` },
    { "name": "Dogpile", "url": "https://www.dogpile.com/", "icon": "https://www.dogpile.com/static/info.dogpile.com/favicon-32x32.png" }
    ],
  "Social" : [
    {"name": "Whatsapp", "url": "https://web.whatsapp.com/"},
    {"name": "LinkedIn", "url": "https://www.linkedin.com/", "icon": `${wmc}/8/81/LinkedIn_icon.svg`, "background": "#007ebb"},
    {"name": "Threads", "url": "https://www.threads.net", "icon": `${wmc}/9/9d/Threads_%28app%29_logo.svg`},
    {"name": "Instagram", "url": "https://www.instagram.com", "icon": `${wmc}/e/e7/Instagram_logo_2016.svg`},
    {"name": "BlueSky", "url": "https://bsky.app"},
    {"name": "Reddit", "url": "https://www.reddit.com/"},
    {"name": "Pinterest", "url": "https://www.pinterest.com/", "icon": `${wmc}/4/4d/Pinterest.svg`, "b": "#bd081c"},
    {"name": "TikTok", "url": "https://www.tiktok.com/", "icon": `${wmc}/3/34/Ionicons_logo-tiktok.svg`},
    {"name": "Twitter", "url": "https://x.com", "icon": `${wmc}/6/6f/Logo_of_Twitter.svg`},
    {"name": "Facebook","url": "https://www.facebook.com", "icon": `${wmc}/5/51/Facebook_f_logo_%282019%29.svg`, "b": "#1977f3"},
    {"name": "Telegram", "url": "https://web.telegram.org/", "icon": `${wmc}/8/83/Telegram_2019_Logo.svg`, "b": "#29aaec"},
    {"name": "Airbnb", "url": "https://www.airbnb.com/", "background": "#ff5a5f"},
    {"name": "Booking", "url": "https://www.booking.com/", "background": "#003b95"}
  ],
  "Streaming" : [
    {"name": "Spotify", "url": "https://open.spotify.com/", "icon": `${wmc}/8/84/Spotify_icon.svg`},
    {"name": "Youtube", "url": "https://www.youtube.com/", "icon": `${wmc}/0/09/YouTube_full-color_icon_%282017%29.svg`},
    {"name": "YoutubeMusic", "url": "https://music.youtube.com/", "icon": `${wmc}/6/6a/Youtube_Music_icon.svg`},
    {"name": "DailyMotion", "url": "https://www.dailymotion.com/"},
    {"name": "SoundCloud", "url": "https://soundcloud.com/", "icon": `${wmc}/a/a2/Antu_soundcloud.svg`, "background": "#ff5500"},
    "break",
    {"name": "Netflix", "url": "https://netflix.com/"},
    {"name": "Prime", "url": "https://www.primevideo.com/", "background": "#0578ff"},
    {"name": "HBO", "url": "https://www.hbomax.com/", "background": "#000"},
    {"name": "Disney+", "url": "https://www.disneyplus.com/"},
    {"name": "YTTV", "url": "https://tv.youtube.com/"},
    {"name": "Curiosity", "url": "https://curiositystream.com/"},
    {"name": "NBC", "url": "https://www.nbcuniversal.com/", "background": "#400371"},
    {"name": "NOS", "url": "https://nostv.pt/"},
    {"name": "Vodafone", "url": "https://tv.vodafone.pt/"},
    {"name": "MEO", "url": "https://meogo.meo.pt/"},
    ],
  "Office": [
    {"name": "Office365", "url": "https://www.office.com/", "icon": `${wmc}/0/0e/Microsoft_365_%282022%29.svg` },
    {"name": "Outlook", "url": "https://outlook.live.com/mail/0/", "icon": `${wmc}/c/cc/Microsoft_Outlook_Icon_%282025–present%29.svg` },
    {"name": "Calendar", "url": "https://outlook.live.com/calendar/0/view/month"},
    {"name": "People", "url": "https://outlook.live.com/people/0/"},
    {"name": "Onedrive", "url": "https://onedrive.live.com/", "icon": `${wmc}/e/e7/Microsoft_OneDrive_Icon_%282025_-_present%29.svg` },    
    {"name": "Excel", "url": "https://www.microsoft365.com/launch/excel?auth=1", "icon": `${wmc}/6/60/Microsoft_Office_Excel_%282025%E2%80%93present%29.svg`},
    {"name": "Word", "url": "https://www.office.com/launch/word?auth=1", "icon": `${wmc}/e/e8/Microsoft_Office_Word_%282025%E2%80%93present%29.svg`},
    {"name": "PowerPoint", "url": "https://www.office.com/launch/powerpoint?auth=1", "icon": `${wmc}/d/df/Microsoft_Office_PowerPoint_%282025%E2%80%93present%29.svg`},
    {"name": "OneNote", "url": "https://www.onenote.com/notebooks?auth=1", "icon": `${wmc}/3/34/Microsoft_OneNote_Icon_%282025_-_present%29.svg`},
    {"name": "Teams", "url": "https://teams.live.com/", "icon": `${wmc}/0/07/Microsoft_Office_Teams_%282025–present%29.svg`},
    {"name": "Sharepoint", "url": "https://sharepoint.live.com/", "icon": `${wmc}/2/28/Microsoft_Office_SharePoint_%282025–present%29.svg`},
    {"name": "Designer", "url": "https://designer.microsoft.com/home"},
    "break",
    {"name": "Account", "url": "https://myaccount.google.com/u/0/"},
    {"name": "Keep", "url": "https://keep.google.com/"},
    {"name": "Find", "url": "https://www.google.com/android/find/", "icon": `${wmc}/d/dc/Google_Find_My_Device_2023.svg`},
    {"name": "GMail", "url": "https://mail.google.com/mail/u/0/#inbox", "icon": `${wmc}/7/7e/Gmail_icon_%282020%29.svg`},
    {"name": "Calendar", "url": "https://calendar.google.com/calendar/u/0/", "icon": `${wmc}/a/a5/Google_Calendar_icon_%282020%29.svg`},
    {"name": "Contacts", "url": "https://contacts.google.com/u/0/", "icon": `${wmc}/a/a8/Google_Contacts_icon_%282022%29.svg`},
    {"name": "Drive", "url": "https://drive.google.com/drive/my-drive", "icon": `${wmc}/1/12/Google_Drive_icon_%282020%29.svg`},
    {"name": "Photos", "url": "https://photos.google.com/u/0/"},
    {"name": "Maps", "url": "https://www.google.com/maps/u/0/", "icon": `${wmc}/a/aa/Google_Maps_icon_%282020%29.svg`},
    {"name": "Books", "url": "https://books.google.com/u/0/", "icon": `${wmc}/1/11/Google_Play_Books_icon_%282023%29.svg`},
    {"name": "Translate", "url": "https://translate.google.com", "icon": `${wmc}/d/d7/Google_Translate_logo.svg`},
    {"name": "Docs", "url": "https://docs.google.com/document/u/0/", "icon": `${wmc}/6/66/Google_Docs_2020_Logo.svg`},
    {"name": "Sheets", "url": "https://docs.google.com/spreadsheets/u/0/", "icon": `${wmc}/a/ae/Google_Sheets_2020_Logo.svg`},
    {"name": "Slides", "url": "https://docs.google.com/presentation/u/0/", "icon": `${wmc}/1/16/Google_Slides_2020_Logo.svg`},
    {"name": "Forms", "url": "https://docs.google.com/forms/u/0/", "icon": `${wmc}/5/5b/Google_Forms_2020_Logo.svg`},
    {"name": "Play", "url": "https://play.google.com/store/apps"},
    {"name": "Meet", "url": "https://meet.google.com/u/0/"},
    {"name": "Chat", "url": "https://chat.google.com/u/0/"},
    {"name": "ShoppingList", "url": "https://shoppinglist.google.com/", "icon": `${wmc}/c/ce/Google_Shopping.svg`},
    ],
  "Shopping": [
    {"name": "Amazon", "url": "https://www.amazon.es/", "icon": `${wmc}/4/4a/Amazon_icon.svg`},
    {"name": "eBay", "url": "https://www.ebay.es/", "icon": `${wmc}/1/1b/EBay_logo.svg`},
    {"name": "Temu", "url": "https://www.temu.com/" },
    {"name": "AliExpress", "url": "https://best.aliexpress.com/"},
    {"name": "KuantoKusta", "url": "https://www.kuantokusta.pt/"},
    {"name": "BackMarket", "url": "https://www.backmarket.pt/", "background": "#dbfb6c"},
    {"name": "Refurbed", "url": "https://www.refurbed.pt/", "background": "#332e80"},
    {"name": "OLX", "url": "https://www.olx.pt/", "background": "#23e5db"},
    {"name": "WeBuy/CeX", "url": "https://pt.webuy.com/", "background": "#fe0002"},
    "break",
    {"name": "PingoDoce", "url": "https://www.pingodoce.pt/?"},
    {"name": "Continente", "url": "https://www.continente.pt/"},
    {"name": "Auchan", "url": "https://www.auchan.pt/"},
    {"name": "Lidl", "url": "https://www.lidl.pt/" },
    {"name": "Aldi", "url": "https://www.aldi.pt/"},
    {"name": "Intermarche", "url": "https://www.loja-online.intermarche.pt/"},
    "break",
    {"name": "Fnac", "url": "https://www.fnac.pt/", "icon": `${wmc}/2/2e/Fnac_Logo.svg`},    
    {"name": "Worten", "url": "https://www.worten.pt/", "icon": "https://www.worten.pt/apple-touch-icon.png", "background": "#e41a15"},
    {"name": "Darty", "url": "https://darty.pt/", "background": "#ed1c27"},
    {"name": "RadioPopular", "url": "https://www.radiopopular.pt/"},
    {"name": "PCDiga", "url": "https://www.pcdiga.com/"},
    {"name": "GlobalData", "url": "https://www.globaldata.pt/"},
    {"name": "NovoAtalho", "url": "https://www.novoatalho.pt/"},
    {"name": "Mauser", "url": "https://mauser.pt", "background": "#ffd200"},
    {"name": "Castro", "url": "https://www.castroelectronica.pt/"},
    {"name": "Aquario", "url": "https://www.aquario.pt/"},
    "break",
    {"name": "Ikea", "url": "https://www.ikea.com/pt/pt/", "icon": `${wmc}/c/c5/Ikea_logo.svg` },
    {"name": "Bricodepot", "url": "https://www.bricodepot.pt/"},
    {"name": "Leroy", "url": "https://www.leroymerlin.pt/"},
    {"name": "ZaraHome", "url": "https://www.zarahome.com/pt/", "icon_b": `${wmc}/f/fd/Zara_Logo.svg`},
    {"name": "Shein", "url": "https://pt.shein.com/", "background": "black"},
    {"name": "Mango", "url": "https://shop.mango.com/", "icon_b": `${wmc}/1/1c/Logo_of_Mango_%28new%29.svg`},
    {"name": "MaisGasolina", "url": "https://www.maisgasolina.com", "user": "1"},
    {"name": "PoupaPilim", "url": "https://poupapilim.com", "user": "1"},
    "break",
    {"name": "Google", "url": "https://store.google.com/"},
    {"name": "Apple", "url": "https://www.apple.com/"},
    {"name": "Oppo", "url": "https://www.oppo.com/"},
    {"name": "OnePlus", "url":"https://www.oneplus.com/", "background": "#f51220"},
    {"name": "Samsung", "url":"https://www.samsung.com/"},
    {"name": "Xiaomi", "url": "https://www.xiaomistore.pt/", "icon": `${wmc}/a/ae/Xiaomi_logo_%282021-%29.svg`},
    {"name": "Realme", "url": "https://www.realme.com/eu/", "icon": `${wmc}/1/1d/Realme-realme-_logo_box-RGB-01.svg`, "background": "#ffc915"},
    {"name": "Chuwi", "url": "https://www.chuwi.com/pt/", "icon": `${wmc}/7/7e/Chuwi_logo_2019.png`},
  ],
  "Dev": [
    {"name": "StackOverflow", "url": "https://stackoverflow.com/"},
    {"name": "MediaInfo","url": "https://mediaarea.net/MediaInfoOnline"},
    {"name": "VSCode", "url": "https://insiders.vscode.dev", "icon": `${wmc}/4/4b/Visual_Studio_Code_Insiders_1.36_icon.svg`},
    {"name": "Github", "url": "https://github.com", "icon": `${wmc}/9/91/Octicons-mark-github.svg`},
    {"name": "CodePen", "url": "https://codepen.io", "icon": `${wmc}/6/6d/Ionicons_logo-codepen.svg`},
    {"name": "CodeSandbox", "url": "https://codesandbox.io", "icon": `${wmc}/5/5f/Feather-logos-codesandbox.svg`},
    {"name": "ShaderToy", "url": "https://www.shadertoy.com", "icon": 'https://cdn.brandfetch.io/id0YlYrikl/w/400/h/400/theme/dark/icon.png?c=1bxid64Mup7aczewSAYMX&t=1756992478950'},
    {"name": "ShaderFrog", "url": "https://shaderfrog.com/app/"},
    {"name": "Codeit", "url": "https://codeit.codes/", "icon": "https://codeit.codes/icons/iphone-app-180.png", "background": "black"},
    {"name": "Python", "url": "https://www.programiz.com/python-programming/online-compiler/", "icon": `${wmc}/1/1f/Python_logo_01.svg`},
    {"name": "Javascript", "url": "https://www.programiz.com/javascript/online-compiler/", "icon": `${wmc}/3/3b/Javascript_Logo.png`, "background": "#f7df1e"},
    {"name": "Java", "url": "https://www.programiz.com/java-programming/online-compiler/", "icon": "https://upload.wikimedia.org/wikipedia/pt/3/30/Java_programming_language_logo.svg"},
    {"name": "C", "url": "https://www.programiz.com/c-programming/online-compiler/", "icon": `${wmc}/1/18/C_Programming_Language.svg`},
    {"name": "C++", "url": "https://www.programiz.com/cpp-programming/online-compiler/", "icon": `${wmc}/1/18/ISO_C%2B%2B_Logo.svg`},
    {"name": "Bash", "url": "https://www.tutorialspoint.com/execute_bash_online.php", "icon": `${wmc}/4/4b/Bash_Logo_Colored.svg`},
    "break",
    {"name": "Desmos", "url": "https://www.desmos.com/calculator"},
    {"name": "Overleaf", "url": "https://www.overleaf.com/"},
    {"name": "IT-Tools", "url": "https://it-tools.tech"},
    {"name": "CheatSheets", "url": "https://devhints.io/"},
    {"name": "imgColorPicker", "url": "https://imagecolorpicker.com"},
    {"name": "shapeShifter", "url": "https://shapeshifter.design/" },
    {"name": "WolframAlpha", "url": "https://www.wolframalpha.com/"},
  ]
}